[project]
name = "ctfmelanoma"
version = "0.1.0"
description = "CTF Melanoma"
requires-python = ">= 3.12"

dependencies = [
    "anndata>=0.11.3",
    "numpy>=2.2",
    "pandas>=2.0.0",
    "scipy>=1.16.0",
    "scikit-learn>=1.4.2",
    "tensorly>=0.9.0",
    "matplotlib~=3.10.1",
    "seaborn~=0.13.2",
    "tensorly-viz>=0.1.7",
    "scanpy>=1.12.0",
    "tensorpack @ git+https://github.com/meyer-lab/tensorpack.git@main",
    "scikit-misc>=0.5.2",
]

readme = "README.md"

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # Unused arguments
    "ARG",
]
